CREATE TABLE `data` (
	`nsfw` INT(10) NULL DEFAULT '0',
	`id` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`img` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`comment` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`name` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`createTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
